#!/bin/bash

# Get path of repo directory (the one containing this script)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Update submodules
( cd $DIR && git submodule update --init --recursive )

# Enable RPM Fusion Repos

sudo dnf install "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
"https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

# Install
sudo dnf install $(grep "^[^#]" requirements.txt)

# Set up display manager
sudo systemctl enable sddm
sudo systemctl set-default graphical.target
# Install Display Manager Theme
sudo dnf install qt5-qtquickcontrols qt5-qtgraphicaleffects
sudo sync -avh --chmod=D775,F664 $DIR/sddm-chili /usr/share/sddm/themes/

# Copy config files to users home
rsync -avh $DIR/settings/ $HOME/
# Copy system-config files to /etc
sudo rsync -avh --chmod=D775,F664 $DIR/system-settings/ /etc/

# Disable gnome CSD
sudo dnf copr enable hdfssk/gtk3-nocsd
sudo dnf install gtk3-nocsd

# Set dconf keys
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false
